---
apiVersion: v1
kind: Service

metadata:
  name: nginx-deployment
  namespace: default

spec:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80

  selector:
    app: nginx 

  type: NodePort
   
   
   #kubectl expose deploy name --port --type